Repository U-Final/U-Hyu-be, pull requests merged in 2025-07, with the labels that each got.

#8 [FEAT][UHYU-86] jwt 인증 인가 구현
  .github/PULL_REQUEST_TEMPLATE.md
  build.gradle
  src/main/java/com/ureca/uhyu/domain/auth/handler/OAuth2SuccessHandler.java
  src/main/java/com/ureca/uhyu/domain/auth/jwt/JwtAuthenticationFilter.java
  src/main/java/com/ureca/uhyu/domain/auth/jwt/JwtTokenProvider.java
  src/main/java/com/ureca/uhyu/domain/auth/repository/TokenRepository.java
  src/main/java/com/ureca/uhyu/domain/auth/service/TokenService.java
  src/main/java/com/ureca/uhyu/global/config/PermitAllURI.java
  src/main/java/com/ureca/uhyu/global/config/SecurityConfig.java
  src/main/java/com/ureca/uhyu/global/response/ResultCode.java
Labels: ✨ 기능구현

#14 [FEATURE][UHYU-72] 지도 상세조회 로직 구현 및 JWT관련 어노테이션 도입
  src/main/java/com/ureca/uhyu/domain/auth/dto/CustomUserDetails.java
  src/main/java/com/ureca/uhyu/domain/auth/jwt/JwtAuthenticationFilter.java
  src/main/java/com/ureca/uhyu/domain/auth/service/CustomUserDetailsService.java
  src/main/java/com/ureca/uhyu/domain/brand/entity/Brand.java
  src/main/java/com/ureca/uhyu/domain/map/controller/MapController.java
  src/main/java/com/ureca/uhyu/domain/map/dto/Request/MapReq.java
  src/main/java/com/ureca/uhyu/domain/map/dto/Response/MapRes.java
  src/main/java/com/ureca/uhyu/domain/map/service/MapService.java
  src/main/java/com/ureca/uhyu/domain/map/service/MapServiceImpl.java
  src/main/java/com/ureca/uhyu/domain/store/dto/response/StoreDetailRes.java
  src/main/java/com/ureca/uhyu/domain/store/repository/StoreRepository.java
  src/main/java/com/ureca/uhyu/global/annotation/CurrentUser.java
  src/main/java/com/ureca/uhyu/global/config/PermitAllURI.java
  src/main/java/com/ureca/uhyu/global/config/SecurityConfig.java
  src/main/java/com/ureca/uhyu/global/config/WebConfig.java
  src/main/java/com/ureca/uhyu/global/resolver/CurrentUserArgumentResolver.java
  src/main/java/com/ureca/uhyu/global/response/ResultCode.java
  src/main/resources/db/changelog/2025/07/10-02-changelog.xml
  src/test/java/com/ureca/uhyu/domain/map/service/MapServiceImpl.java
Labels: ✨ 기능구현

#15 [FEAT][UHYU-76] 지도 브랜드 검색 로직 구현
  src/main/java/com/ureca/uhyu/domain/brand/entity/Brand.java
  src/main/java/com/ureca/uhyu/domain/map/controller/MapController.java
  src/main/java/com/ureca/uhyu/domain/map/service/MapService.java
  src/main/java/com/ureca/uhyu/domain/map/service/MapServiceImpl.java
  src/main/java/com/ureca/uhyu/domain/store/repository/StoreRepositoryCustom.java
  src/main/java/com/ureca/uhyu/domain/store/repository/StoreRepositoryImpl.java
  src/test/java/com/ureca/uhyu/domain/map/service/MapServiceImpl.java
  src/test/java/com/ureca/uhyu/domain/map/service/MapServiceImplTest.java
Labels: ✨ 기능구현

#19 [FEAT][UHYU-73] 이중 필터링 구현 및 구현을 위한 코드 리팩토링
  src/main/java/com/ureca/uhyu/domain/map/controller/MapController.java
  src/main/java/com/ureca/uhyu/domain/map/service/MapService.java
  src/main/java/com/ureca/uhyu/domain/map/service/MapServiceImpl.java
  src/main/java/com/ureca/uhyu/domain/store/repository/StoreRepositoryCustom.java
  src/main/java/com/ureca/uhyu/domain/store/repository/StoreRepositoryCustomImpl.java
  src/test/java/com/ureca/uhyu/domain/map/service/MapServiceImplTest.java
Labels: ✨ 기능구현

#22 [FEAT][UHYU-150] TMP_USER(신규 유저)는 extra-info로 리다이렉트되도록 수정
  src/main/java/com/ureca/uhyu/domain/auth/handler/OAuth2SuccessHandler.java
  src/main/java/com/ureca/uhyu/domain/auth/service/CustomOAuth2UserService.java
  src/main/java/com/ureca/uhyu/global/config/SecurityConfig.java
Labels: ✨ 기능구현

#21 [FEAT][UHYU-97] 즐겨찾기 삭제
  src/main/java/com/ureca/uhyu/domain/user/controller/UserController.java
  src/main/java/com/ureca/uhyu/domain/user/service/UserService.java
  src/main/java/com/ureca/uhyu/global/response/ResultCode.java
  src/test/java/com/ureca/uhyu/domain/user/service/UserServiceTest.java
Labels: ✨ 기능구현

#23 [FEAT][UHYU-97] 즐겨찾기 추가/삭제 및 매장상세보기 즐겨찾기 정보 추가
  src/main/java/com/ureca/uhyu/domain/map/controller/MapController.java
  src/main/java/com/ureca/uhyu/domain/map/dto/response/MapBookmarkRes.java
  src/main/java/com/ureca/uhyu/domain/map/service/MapService.java
  src/main/java/com/ureca/uhyu/domain/map/service/MapServiceImpl.java
  src/main/java/com/ureca/uhyu/domain/store/dto/response/StoreDetailRes.java
  src/main/java/com/ureca/uhyu/domain/user/repository/BookmarkListRepository.java
  src/main/java/com/ureca/uhyu/domain/user/repository/BookmarkRepository.java
  src/main/java/com/ureca/uhyu/domain/user/service/UserService.java
  src/main/java/com/ureca/uhyu/global/response/ResultCode.java
  src/test/java/com/ureca/uhyu/domain/map/service/MapServiceImplTest.java
  src/test/java/com/ureca/uhyu/domain/user/service/UserServiceTest.java
Labels: ✨ 기능구현

#25 [FIX][UHYU-159] security swagger 접근 허용
  src/main/java/com/ureca/uhyu/domain/auth/jwt/JwtAuthenticationFilter.java
  src/main/java/com/ureca/uhyu/global/config/SecurityConfig.java
Labels: 🐞 버그

#27 [CHORE][UHYU-159] 배포 리다이렉트 추가
  src/main/java/com/ureca/uhyu/domain/auth/jwt/JwtTokenProvider.java
  src/main/java/com/ureca/uhyu/global/config/SecurityConfig.java
Labels: 리펙토링

#28 [FIX][UHYU-165] 배포 리다이렉트 추가
  src/main/java/com/ureca/uhyu/domain/auth/dto/KakaoUserInfoResponse.java
  src/main/java/com/ureca/uhyu/domain/auth/handler/OAuth2SuccessHandler.java
  src/main/java/com/ureca/uhyu/domain/auth/service/CustomOAuth2UserService.java
  src/main/java/com/ureca/uhyu/global/config/SecurityConfig.java
Labels: 🐞 버그

#32 [FEAT][UHYU-163] 브랜드(제휴처) 상세 조회
  src/main/java/com/ureca/uhyu/domain/auth/repository/TokenRepository.java
  src/main/java/com/ureca/uhyu/domain/brand/controller/BrandController.java
  src/main/java/com/ureca/uhyu/domain/brand/dto/response/BenefitRes.java
  src/main/java/com/ureca/uhyu/domain/brand/dto/response/BrandInfoRes.java
  src/main/java/com/ureca/uhyu/domain/brand/dto/response/BrandRes.java
  src/main/java/com/ureca/uhyu/domain/brand/entity/Benefit.java
  src/main/java/com/ureca/uhyu/domain/brand/repository/BrandRepository.java
  src/main/java/com/ureca/uhyu/domain/brand/service/BrandService.java
  src/main/java/com/ureca/uhyu/domain/recommendation/repository/RecommendationBaseDataRepository.java
  src/main/java/com/ureca/uhyu/domain/user/repository/UserRepository.java
  src/main/java/com/ureca/uhyu/global/response/ResultCode.java
  src/main/resources/db/changelog/2025/07/18-01-changelog.xml
  src/test/java/com/ureca/uhyu/domain/brand/service/BrandServiceTest.java
Labels: ✨ 기능구현

#33 [FEAT]/[UHYU-174] MyMap 리스트 조회
  src/main/java/com/ureca/uhyu/domain/mymap/controller/MyMapController.java
  src/main/java/com/ureca/uhyu/domain/mymap/dto/response/MyMapRes.java
  src/main/java/com/ureca/uhyu/domain/mymap/entity/MyMap.java
  src/main/java/com/ureca/uhyu/domain/mymap/entity/MyMapList.java
  src/main/java/com/ureca/uhyu/domain/mymap/enums/MarkerColor.java
  src/main/java/com/ureca/uhyu/domain/mymap/enums/Visibility.java
  src/main/java/com/ureca/uhyu/domain/mymap/repository/MyMapListRepository.java
  src/main/java/com/ureca/uhyu/domain/mymap/service/MyMapService.java
  src/main/java/com/ureca/uhyu/domain/user/entity/ActionLogs.java
  src/main/java/com/ureca/uhyu/domain/user/entity/History.java
  src/main/resources/db/changelog/2025/07/17-01-changelog.xml
  src/main/resources/db/changelog/2025/07/18-02-changelog.xml
  src/test/java/com/ureca/uhyu/domain/mymap/service/MyMapServiceTest.java
Labels: ✨ 기능구현

#34 [FEAT][UHYU-179] My Map 추가
  src/main/java/com/ureca/uhyu/domain/mymap/controller/MyMapController.java
  src/main/java/com/ureca/uhyu/domain/mymap/dto/request/MyMapReq.java
  src/main/java/com/ureca/uhyu/domain/mymap/dto/response/MyMapRes.java
  src/main/java/com/ureca/uhyu/domain/mymap/entity/MyMapList.java
  src/main/java/com/ureca/uhyu/domain/mymap/enums/Visibility.java
  src/main/java/com/ureca/uhyu/domain/mymap/service/MyMapService.java
  src/main/resources/db/changelog/2025/07/18-03-changelog.xml
  src/test/java/com/ureca/uhyu/domain/mymap/service/MyMapServiceTest.java
Labels: ✨ 기능구현

#37 [FEAT]/[UHYU-182] UUID 기반 My Map 지도 조회 기능 구현
  build.gradle
  src/main/java/com/ureca/uhyu/domain/mymap/controller/MyMapController.java
  src/main/java/com/ureca/uhyu/domain/mymap/dto/request/CreateMyMapListReq.java
  src/main/java/com/ureca/uhyu/domain/mymap/dto/response/MyMapRes.java
  src/main/java/com/ureca/uhyu/domain/mymap/entity/MyMapList.java
  src/main/java/com/ureca/uhyu/domain/mymap/repository/MyMapListRepository.java
  src/main/java/com/ureca/uhyu/domain/mymap/repository/MyMapRepository.java
  src/main/java/com/ureca/uhyu/domain/mymap/service/MyMapService.java
  src/main/resources/db/changelog/2025/07/21-01-changelog.xml
  src/test/java/com/ureca/uhyu/domain/mymap/service/MyMapServiceTest.java
Labels: ✨ 기능구현

#38 [FEAT][UHYU-100] 추천 조회 api 구현
  src/main/java/com/ureca/uhyu/domain/recommendation/controller/RecommendationController.java
  src/main/java/com/ureca/uhyu/domain/recommendation/dto/RecommendationResponse.java
  src/main/java/com/ureca/uhyu/domain/recommendation/entity/Recommendation.java
  src/main/java/com/ureca/uhyu/domain/recommendation/repository/RecommendationRepository.java
  src/main/java/com/ureca/uhyu/domain/recommendation/service/RecommendationService.java
  src/main/java/com/ureca/uhyu/domain/user/entity/ActionLogs.java
  src/main/java/com/ureca/uhyu/global/response/ResultCode.java
  src/test/java/com/ureca/uhyu/domain/recommendation/controller/RecommendationControllerTest.java
Labels: ✨ 기능구현

#39 [FIX][UHYU-100] localDateTime, 변수명 에러 수정
  src/main/java/com/ureca/uhyu/domain/recommendation/dto/RecommendationResponse.java
  src/main/java/com/ureca/uhyu/domain/recommendation/service/RecommendationService.java
Labels: ✨ 기능구현

#40 [FEAT][UHYU-198] My Map 매장 등록 유무 조회 및 일부 코드 리팩토링(온보딩, uuid 기반 mymap 지도 조회)
  src/main/java/com/ureca/uhyu/domain/mymap/controller/MyMapController.java
  src/main/java/com/ureca/uhyu/domain/mymap/dto/response/BookmarkedMyMapListRes.java
  src/main/java/com/ureca/uhyu/domain/mymap/dto/response/BookmarkedMyMapRes.java
  src/main/java/com/ureca/uhyu/domain/mymap/dto/response/MyMapRes.java
  src/main/java/com/ureca/uhyu/domain/mymap/repository/MyMapRepository.java
  src/main/java/com/ureca/uhyu/domain/mymap/service/MyMapService.java
  src/main/java/com/ureca/uhyu/domain/user/entity/BookmarkList.java
  src/main/java/com/ureca/uhyu/domain/user/repository/BookmarkListRepository.java
  src/main/java/com/ureca/uhyu/domain/user/service/UserService.java
  src/main/java/com/ureca/uhyu/global/response/ResultCode.java
  src/main/resources/db/changelog/2025/07/21-02-changelog.xml
  src/test/java/com/ureca/uhyu/domain/mymap/service/MyMapServiceTest.java
  src/test/java/com/ureca/uhyu/domain/user/service/UserServiceTest.java
Labels: ✨ 기능구현

#42 [DOC][UHYU-203] 각 도메인별 컨트롤러 Swagger 명세화 및 보안 설정 추가
  gradlew
  src/main/java/com/ureca/uhyu/domain/auth/controller/AuthController.java
  src/main/java/com/ureca/uhyu/domain/auth/dto/UserEmailCheckRequest.java
  src/main/java/com/ureca/uhyu/domain/brand/controller/BrandController.java
  src/main/java/com/ureca/uhyu/domain/brand/dto/response/BenefitRes.java
  src/main/java/com/ureca/uhyu/domain/brand/dto/response/BrandRes.java
  src/main/java/com/ureca/uhyu/domain/brand/enums/BenefitType.java
  src/main/java/com/ureca/uhyu/domain/map/controller/MapController.java
  src/main/java/com/ureca/uhyu/domain/mymap/controller/MyMapController.java
  src/main/java/com/ureca/uhyu/domain/mymap/enums/MarkerColor.java
  src/main/java/com/ureca/uhyu/domain/recommendation/controller/RecommendationController.java
  src/main/java/com/ureca/uhyu/domain/user/controller/UserController.java
  src/main/java/com/ureca/uhyu/domain/user/dto/request/UpdateUserReq.java
  src/main/java/com/ureca/uhyu/domain/user/dto/request/UserOnboardingRequest.java
  src/main/java/com/ureca/uhyu/domain/user/enums/Gender.java
  src/main/java/com/ureca/uhyu/domain/user/enums/Grade.java
  src/main/java/com/ureca/uhyu/global/config/SwaggerConfig.java
Labels: 📚 문서화

#46 [FEAT][UHYU-78] 카테고리 목록 조회 api 기능 구현
  src/main/java/com/ureca/uhyu/domain/brand/controller/CategoryController.java
  src/main/java/com/ureca/uhyu/domain/brand/dto/response/CategoryListRes.java
  src/main/java/com/ureca/uhyu/domain/brand/service/CategoryService.java
  src/test/java/com/ureca/uhyu/domain/brand/controller/CategoryControllerTest.java
  src/test/java/com/ureca/uhyu/global/config/TestSecurityConfig.java
Labels: ✨ 기능구현

#49 [FIX][UHYU-211] 온보딩 정보 USER DB 저장 에러 수정
  .gitignore
  build.gradle
  src/main/java/com/ureca/uhyu/domain/auth/dto/KakaoUserInfoResponse.java
  src/main/java/com/ureca/uhyu/domain/auth/jwt/JwtAuthenticationFilter.java
  src/main/java/com/ureca/uhyu/domain/auth/mapper/UserInfoMapper.java
  src/main/java/com/ureca/uhyu/domain/auth/service/CustomOAuth2UserService.java
  src/main/java/com/ureca/uhyu/domain/user/dto/response/GetUserInfoRes.java
  src/main/java/com/ureca/uhyu/domain/user/entity/User.java
  src/main/java/com/ureca/uhyu/domain/user/service/UserService.java
  src/main/resources/application-dev.yml
  src/main/resources/application-prod.yml
  src/main/resources/db/changelog/2025/07/21-01-changelog.xml
  src/main/resources/db/changelog/2025/07/23-01-changelog.xml
  src/test/java/com/ureca/uhyu/domain/mymap/service/MyMapServiceTest.java
  src/test/java/com/ureca/uhyu/domain/user/service/UserServiceTest.java
Labels: 🐞 버그

#51 [FEAT][UHYU-211] 온보딩 관심 및 방문 브랜드 저장 String -> Long 변경
  src/main/java/com/ureca/uhyu/domain/user/dto/request/UserOnboardingRequest.java
  src/main/java/com/ureca/uhyu/domain/user/service/UserService.java
Labels: ✨ 기능구현, 🐞 버그

#57 [FEAT][UHYU-217] 카테고리별 필터링 횟수 통계
  src/main/java/com/ureca/uhyu/domain/admin/controller/AdminController.java
  src/main/java/com/ureca/uhyu/domain/admin/dto/response/StatisticsFilterByCategoryRes.java
  src/main/java/com/ureca/uhyu/domain/admin/service/AdminService.java
  src/main/java/com/ureca/uhyu/domain/user/repository/actionLogs/ActionLogsRepository.java
  src/main/java/com/ureca/uhyu/domain/user/repository/actionLogs/ActionLogsRepositoryCustom.java
  src/main/java/com/ureca/uhyu/domain/user/repository/actionLogs/ActionLogsRepositoryCustomImpl.java
  src/main/java/com/ureca/uhyu/domain/user/repository/bookmark/BookmarkRepository.java
  src/main/java/com/ureca/uhyu/domain/user/repository/bookmark/BookmarkRepositoryCustom.java
  src/main/java/com/ureca/uhyu/domain/user/repository/bookmark/BookmarkRepositoryCustomImpl.java
  src/test/java/com/ureca/uhyu/domain/admin/service/AdminServiceTest.java
Labels: ✨ 기능구현

#58 [FEAT][UHYU-219] 카테고리, 브랜드별 추천 통계
  src/main/java/com/ureca/uhyu/domain/admin/controller/AdminController.java
  src/main/java/com/ureca/uhyu/domain/admin/dto/response/BookmarksByBrand.java
  src/main/java/com/ureca/uhyu/domain/admin/dto/response/BookmarksByCategoryRes.java
  src/main/java/com/ureca/uhyu/domain/admin/dto/response/CountRecommendationRes.java
  src/main/java/com/ureca/uhyu/domain/admin/dto/response/RecommendationsByBrand.java
  src/main/java/com/ureca/uhyu/domain/admin/dto/response/StatisticsBookmarkRes.java
  src/main/java/com/ureca/uhyu/domain/admin/service/AdminService.java
  src/main/java/com/ureca/uhyu/domain/recommendation/repository/RecommendationRepositoryCustom.java
  src/main/java/com/ureca/uhyu/domain/recommendation/repository/RecommendationRepositoryCustomImpl.java
  src/test/java/com/ureca/uhyu/domain/admin/service/AdminServiceTest.java
Labels: ✨ 기능구현

#60 [FEAT][UHYU-246] 유저 action-logs 저장 api 기능 구현
  src/main/java/com/ureca/uhyu/domain/user/controller/UserController.java
  src/main/java/com/ureca/uhyu/domain/user/controller/UserControllerDocs.java
  src/main/java/com/ureca/uhyu/domain/user/dto/request/ActionLogsReq.java
  src/main/java/com/ureca/uhyu/domain/user/dto/request/UserOnboardingReq.java
  src/main/java/com/ureca/uhyu/domain/user/dto/response/ActionLogsRes.java
  src/main/java/com/ureca/uhyu/domain/user/dto/response/UserOnboardingRes.java
  src/main/java/com/ureca/uhyu/domain/user/service/UserService.java
  src/test/java/com/ureca/uhyu/domain/user/service/UserServiceTest.java
Labels: ✨ 기능구현

#59 [FEAT][UHYU-220] 카테고리, 브랜드별 멤버십 사용횟수 통계
  src/main/java/com/ureca/uhyu/domain/admin/controller/AdminController.java
  src/main/java/com/ureca/uhyu/domain/admin/dto/response/MembershipUsageByBrand.java
  src/main/java/com/ureca/uhyu/domain/admin/dto/response/StatisticsFilterRes.java
  src/main/java/com/ureca/uhyu/domain/admin/dto/response/StatisticsMembershipUsageRes.java
  src/main/java/com/ureca/uhyu/domain/admin/dto/response/StatisticsRecommendationRes.java
  src/main/java/com/ureca/uhyu/domain/admin/service/AdminService.java
  src/main/java/com/ureca/uhyu/domain/recommendation/repository/RecommendationRepositoryCustom.java
  src/main/java/com/ureca/uhyu/domain/recommendation/repository/RecommendationRepositoryCustomImpl.java
  src/main/java/com/ureca/uhyu/domain/user/repository/actionLogs/ActionLogsRepositoryCustom.java
  src/main/java/com/ureca/uhyu/domain/user/repository/actionLogs/ActionLogsRepositoryCustomImpl.java
  src/main/java/com/ureca/uhyu/domain/user/repository/history/HistoryRepositoryCustom.java
  src/main/java/com/ureca/uhyu/domain/user/repository/history/HistoryRepositoryCustomImpl.java
  src/test/java/com/ureca/uhyu/domain/admin/service/AdminServiceTest.java
Labels: ✨ 기능구현

#63 [FEAT][UHYU-254] 브랜드 로고 이미지 저장 유틸 클래스 생성
  src/main/java/com/ureca/uhyu/domain/brand/repository/BrandRepository.java
  src/main/java/com/ureca/uhyu/domain/map/controller/MapController.java
  src/main/java/com/ureca/uhyu/domain/map/controller/MapControllerDocs.java
  src/main/java/com/ureca/uhyu/domain/map/dto/response/MapRes.java
  src/main/java/com/ureca/uhyu/domain/map/service/MapService.java
  src/main/java/com/ureca/uhyu/domain/user/service/BarcodeServiceImpl.java
  src/main/java/com/ureca/uhyu/global/util/S3Uploader.java
  src/main/java/com/ureca/uhyu/script/BrandLogoSqlGenerator.java
Labels: ✨ 기능구현

#61 [FEAT][UHYU-267] 방문 매장 저장 api 구현
  src/main/java/com/ureca/uhyu/domain/user/controller/UserController.java
  src/main/java/com/ureca/uhyu/domain/user/controller/UserControllerDocs.java
  src/main/java/com/ureca/uhyu/domain/user/dto/request/SaveRecentVisitReq.java
  src/main/java/com/ureca/uhyu/domain/user/dto/response/ActionLogsRes.java
  src/main/java/com/ureca/uhyu/domain/user/dto/response/SaveUserInfoRes.java
  src/main/java/com/ureca/uhyu/domain/user/service/UserService.java
  src/main/java/com/ureca/uhyu/global/response/ResultCode.java
  src/test/java/com/ureca/uhyu/domain/user/service/UserServiceTest.java
Labels: ✨ 기능구현

#62 [FEAT][UHYU-221] 전체 통계 조회
  src/main/java/com/ureca/uhyu/domain/admin/controller/AdminController.java
  src/main/java/com/ureca/uhyu/domain/admin/dto/response/StatisticsTotalRes.java
  src/main/java/com/ureca/uhyu/domain/admin/service/AdminService.java
  src/main/java/com/ureca/uhyu/domain/user/repository/actionLogs/ActionLogsRepository.java
  src/test/java/com/ureca/uhyu/domain/admin/service/AdminServiceTest.java
Labels: ✨ 기능구현

#76 [FEAT][UHYU-275] 선호 브랜드 목록 조회
  src/main/java/com/ureca/uhyu/domain/brand/controller/BrandController.java
  src/main/java/com/ureca/uhyu/domain/brand/dto/response/InterestBrandRes.java
  src/main/java/com/ureca/uhyu/domain/brand/repository/BrandRepository.java
  src/main/java/com/ureca/uhyu/domain/brand/service/BrandService.java
  src/test/java/com/ureca/uhyu/domain/brand/service/BrandServiceTest.java
Labels: ✨ 기능구현

#79 [FEAT][UHYU-295] uuid 기반 my map 비회원 조회
  src/main/java/com/ureca/uhyu/domain/mymap/controller/MyMapController.java
  src/main/java/com/ureca/uhyu/domain/mymap/controller/MyMapControllerDocs.java
  src/main/java/com/ureca/uhyu/domain/mymap/service/MyMapService.java
  src/main/java/com/ureca/uhyu/global/config/PermitAllURI.java
  src/main/java/com/ureca/uhyu/global/config/SecurityConfig.java
  src/test/java/com/ureca/uhyu/domain/mymap/service/MyMapServiceTest.java
Labels: ✨ 기능구현

#80 [FEATURE][UHYU-102] 비로그인 사용자 대상 인기 브랜드 Top3 제공 api 기능 구현, guest 도메인 분리
  src/main/java/com/ureca/uhyu/domain/brand/controller/BrandController.java
  src/main/java/com/ureca/uhyu/domain/brand/controller/BrandControllerDocs.java
  src/main/java/com/ureca/uhyu/domain/guest/controller/GuestController.java
  src/main/java/com/ureca/uhyu/domain/guest/controller/GuestControllerDocs.java
  src/main/java/com/ureca/uhyu/domain/guest/dto/response/GuestRecommendationRes.java
  src/main/java/com/ureca/uhyu/domain/guest/service/GuestService.java
  src/main/java/com/ureca/uhyu/domain/mymap/controller/MyMapController.java
  src/main/java/com/ureca/uhyu/domain/mymap/controller/MyMapControllerDocs.java
  src/main/java/com/ureca/uhyu/domain/mymap/service/MyMapService.java
  src/main/java/com/ureca/uhyu/domain/recommendation/controller/RecommendationController.java
  src/main/java/com/ureca/uhyu/domain/recommendation/controller/RecommendationControllerDocs.java
  src/main/java/com/ureca/uhyu/domain/recommendation/dto/response/RecommendationRes.java
  src/main/java/com/ureca/uhyu/domain/recommendation/repository/RecommendationRepositoryCustom.java
  src/main/java/com/ureca/uhyu/domain/recommendation/repository/RecommendationRepositoryCustomImpl.java
  src/main/java/com/ureca/uhyu/domain/recommendation/service/RecommendationService.java
  src/main/java/com/ureca/uhyu/global/config/SecurityConfig.java
  src/main/java/com/ureca/uhyu/global/response/ResultCode.java
  src/main/java/com/ureca/uhyu/global/util/TokenCookieUtil.java
  src/test/java/com/ureca/uhyu/domain/mymap/service/MyMapServiceTest.java
  src/test/java/com/ureca/uhyu/domain/recommendation/controller/RecommendationControllerTest.java
  src/test/java/com/ureca/uhyu/domain/recommendation/service/RecommendationServiceTest.java
Labels: ✨ 기능구현, ♻️ 리펙토링

#85 [DOCS] ReadME 2차 멘토링 전 수정
  README.md
Labels: 📚 문서화

#82 [REFACTOR][UHYU-298] 관리자 즐겨찾기 + My Map 통계 기능 쿼리 수정 및 최적화
  src/main/java/com/ureca/uhyu/domain/admin/service/AdminService.java
  src/main/java/com/ureca/uhyu/domain/user/repository/bookmark/BookmarkRepositoryCustom.java
  src/main/java/com/ureca/uhyu/domain/user/repository/bookmark/BookmarkRepositoryCustomImpl.java
  src/test/java/com/ureca/uhyu/domain/admin/service/AdminServiceTest.java
  src/test/java/com/ureca/uhyu/domain/recommendation/service/RecommendationServiceTest.java
Labels: ♻️ 리펙토링
