Repository U-Final/U-Hyu-be, pull requests merged in 2025-08, with the labels that each got.

#87 [FIX][UHYU-329] MyMapList 엔티티 수정
  src/main/java/com/ureca/uhyu/domain/mymap/entity/MyMapList.java
  src/main/resources/db/changelog/2025/07/31-01-changelog.xml
Labels: 🐞 버그

#88 [FEAT][UHYU-328]: 지도 즐겨찾기 매장 조회 로직 수정 및 Grade별 Benefit 로직 리팩토링
  src/main/java/com/ureca/uhyu/domain/brand/entity/Brand.java
  src/main/java/com/ureca/uhyu/domain/map/controller/MapController.java
  src/main/java/com/ureca/uhyu/domain/map/dto/response/MapRes.java
  src/main/java/com/ureca/uhyu/domain/map/service/MapService.java
  src/main/java/com/ureca/uhyu/domain/map/service/MapServiceImpl.java
  src/main/java/com/ureca/uhyu/global/response/ResultCode.java
Labels: ✨ 기능구현

#100 [FIX][UHYU-340] : user/onboarding NTE에러 해결
  src/main/java/com/ureca/uhyu/domain/auth/filter/TmpUserRedirectFilter.java
  src/main/java/com/ureca/uhyu/global/config/PermitAllURI.java
Labels: 🐞 버그

#97 [FIX][UHYU-335] 추천 브랜드 기반 근처 매장 조회 로직 수정 및 문제 해결
  src/main/java/com/ureca/uhyu/domain/map/controller/MapController.java
  src/main/java/com/ureca/uhyu/domain/map/controller/MapControllerDocs.java
  src/main/java/com/ureca/uhyu/domain/map/dto/response/MapRes.java
  src/main/java/com/ureca/uhyu/domain/map/service/MapService.java
  src/main/java/com/ureca/uhyu/domain/map/service/MapServiceImpl.java
  src/main/java/com/ureca/uhyu/domain/store/repository/StoreRepositoryCustom.java
  src/main/java/com/ureca/uhyu/domain/store/repository/StoreRepositoryCustomImpl.java
  src/test/java/com/ureca/uhyu/domain/map/service/MapServiceImplTest.java
Labels: ✨ 기능구현, 🐞 버그

#102 [FIX][UHYU-340] 추천 브랜드 싫어요 선택 시 brandId -> storeId 받도록 수정
  src/main/java/com/ureca/uhyu/domain/recommendation/controller/RecommendationControllerDocs.java
  src/main/java/com/ureca/uhyu/domain/recommendation/dto/request/ExcludeBrandRequest.java
  src/main/java/com/ureca/uhyu/domain/recommendation/service/RecommendationBaseDataService.java
Labels: 🐞 버그

#111 [FIX][UHYU-340] 추천 브랜드 싫어요 선택 시 storeId -> brandId 받도록 수정
  src/main/java/com/ureca/uhyu/domain/recommendation/controller/RecommendationControllerDocs.java
  src/main/java/com/ureca/uhyu/domain/recommendation/dto/request/ExcludeBrandRequest.java
  src/main/java/com/ureca/uhyu/domain/recommendation/service/RecommendationBaseDataService.java
Labels: 🐞 버그

#115 [REFACTOR][UHYU-321] 통계 쿼리 변경 및 통계 데이터 저장 이벤트 처리 로직 추가
  src/main/java/com/ureca/uhyu/domain/admin/controller/AdminController.java
  src/main/java/com/ureca/uhyu/domain/admin/dto/StatisticsDto.java
  src/main/java/com/ureca/uhyu/domain/admin/dto/response/StatisticsBookmarkMyMapRes.java
  src/main/java/com/ureca/uhyu/domain/admin/dto/response/StatisticsTotalRes.java
  src/main/java/com/ureca/uhyu/domain/admin/entity/Statistics.java
  src/main/java/com/ureca/uhyu/domain/admin/enums/StatisticsType.java
  src/main/java/com/ureca/uhyu/domain/admin/repository/StatisticsRepository.java
  src/main/java/com/ureca/uhyu/domain/admin/repository/StatisticsRepositoryCustom.java
  src/main/java/com/ureca/uhyu/domain/admin/repository/StatisticsRepositoryCustomImpl.java
  src/main/java/com/ureca/uhyu/domain/admin/service/AdminService.java
  src/main/java/com/ureca/uhyu/domain/map/event/BookmarkEventListener.java
  src/main/java/com/ureca/uhyu/domain/map/event/BookmarkToggledEvent.java
  src/main/java/com/ureca/uhyu/domain/map/service/MapServiceImpl.java
  src/main/java/com/ureca/uhyu/domain/mymap/event/MyMapEventListener.java
  src/main/java/com/ureca/uhyu/domain/mymap/event/MyMapToggledEvent.java
  src/main/java/com/ureca/uhyu/domain/mymap/service/MyMapService.java
  src/main/java/com/ureca/uhyu/domain/user/event/FilterUsedEvent.java
  src/main/java/com/ureca/uhyu/domain/user/event/FilterUsedEventListener.java
  src/main/java/com/ureca/uhyu/domain/user/event/MembershipUsedEvent.java
  src/main/java/com/ureca/uhyu/domain/user/event/MembershipUsedEventListener.java
  src/main/java/com/ureca/uhyu/domain/user/repository/bookmark/BookmarkRepositoryCustom.java
  src/main/java/com/ureca/uhyu/domain/user/repository/bookmark/BookmarkRepositoryCustomImpl.java
  src/main/java/com/ureca/uhyu/domain/user/service/UserService.java
  src/main/resources/db/changelog/2025/08/04-02-changelog.xml
  src/test/java/com/ureca/uhyu/domain/admin/service/AdminServiceTest.java
Labels: ✨ 기능구현, ♻️ 리펙토링

#114 [FEAT][UHYU-389] 신규유저 추천로직 추가
  src/main/java/com/ureca/uhyu/domain/recommendation/event/RecommendationEvent.java
  src/main/java/com/ureca/uhyu/domain/recommendation/event/RecommendationEventListener.java
  src/main/java/com/ureca/uhyu/domain/recommendation/service/RecommendationBaseDataService.java
  src/main/java/com/ureca/uhyu/domain/user/service/UserService.java
Labels: ✨ 기능구현

#121 [REFACTOR][UHYU-398] 이벤트 리스너 @TransactionalEventListener로 변경
  src/main/java/com/ureca/uhyu/domain/admin/service/AdminService.java
  src/main/java/com/ureca/uhyu/domain/map/event/BookmarkEventListener.java
  src/main/java/com/ureca/uhyu/domain/mymap/event/MyMapEventListener.java
  src/main/java/com/ureca/uhyu/domain/user/event/FilterUsedEventListener.java
  src/main/java/com/ureca/uhyu/domain/user/event/MembershipUsedEventListener.java
  src/main/resources/application-dev.yml
  src/test/java/com/ureca/uhyu/domain/admin/service/AdminServiceTest.java
  src/test/java/com/ureca/uhyu/domain/map/service/MapServiceImplTest.java
  src/test/java/com/ureca/uhyu/domain/mymap/service/MyMapServiceTest.java
  src/test/java/com/ureca/uhyu/domain/user/service/UserServiceTest.java
Labels: ♻️ 리펙토링, 🐞 버그

#122 [FEATURE][UHYU-415] 어드민 브랜드 수정 put -> patch 수정
  src/main/java/com/ureca/uhyu/domain/admin/controller/AdminController.java
  src/main/java/com/ureca/uhyu/domain/brand/controller/BrandController.java
  src/main/java/com/ureca/uhyu/domain/brand/dto/request/UpdateBrandReq.java
  src/main/java/com/ureca/uhyu/domain/brand/entity/Brand.java
  src/main/java/com/ureca/uhyu/domain/brand/repository/BrandRepository.java
  src/main/java/com/ureca/uhyu/domain/brand/service/BrandService.java
  src/main/resources/application-test.yml
  src/test/java/com/ureca/uhyu/UhyuApplicationTests.java
  src/test/java/com/ureca/uhyu/domain/map/service/MapServiceImplTest.java
  src/test/java/com/ureca/uhyu/domain/mymap/service/MyMapServiceTest.java
  src/test/java/com/ureca/uhyu/domain/user/service/UserServiceTest.java
Labels: ✨ 기능구현

#131 [REFACTOR][UHYU-433] 전반적인 코드 리팩토링
  src/main/java/com/ureca/uhyu/domain/admin/dto/BookmarksByBrand.java
  src/main/java/com/ureca/uhyu/domain/admin/dto/MembershipUsageByBrand.java
  src/main/java/com/ureca/uhyu/domain/admin/dto/RecommendationsByBrand.java
  src/main/java/com/ureca/uhyu/domain/admin/dto/StatisticsDto.java
  src/main/java/com/ureca/uhyu/domain/admin/dto/response/StatisticsBookmarkMyMapRes.java
  src/main/java/com/ureca/uhyu/domain/admin/dto/response/StatisticsMembershipUsageRes.java
  src/main/java/com/ureca/uhyu/domain/admin/dto/response/StatisticsRecommendationRes.java
  src/main/java/com/ureca/uhyu/domain/admin/dto/response/UserBrandPair.java
  src/main/java/com/ureca/uhyu/domain/admin/service/AdminService.java
  src/main/java/com/ureca/uhyu/domain/auth/controller/AuthController.java
  src/main/java/com/ureca/uhyu/domain/auth/controller/AuthControllerDocs.java
  src/main/java/com/ureca/uhyu/domain/auth/jwt/JwtTokenProvider.java
  src/main/java/com/ureca/uhyu/domain/auth/service/AuthService.java
  src/main/java/com/ureca/uhyu/domain/brand/controller/BrandController.java
  src/main/java/com/ureca/uhyu/domain/brand/dto/request/UpdateBrandReq.java
  src/main/java/com/ureca/uhyu/domain/brand/dto/response/BrandNameRes.java
  src/main/java/com/ureca/uhyu/domain/brand/dto/response/CategoryListRes.java
  src/main/java/com/ureca/uhyu/domain/brand/dto/response/CreateUpdateBrandRes.java
  src/main/java/com/ureca/uhyu/domain/brand/dto/response/InterestBrandRes.java
  src/main/java/com/ureca/uhyu/domain/brand/entity/Category.java
  src/main/java/com/ureca/uhyu/domain/brand/repository/BrandRepository.java
  src/main/java/com/ureca/uhyu/domain/brand/service/BrandService.java
  src/main/java/com/ureca/uhyu/domain/guest/dto/response/GuestRecommendationRes.java
  src/main/java/com/ureca/uhyu/domain/map/controller/MapController.java
  src/main/java/com/ureca/uhyu/domain/mymap/dto/request/UpdateMyMapListReq.java
  src/main/java/com/ureca/uhyu/domain/mymap/dto/response/BookmarkedMyMapListRes.java
  src/main/java/com/ureca/uhyu/domain/mymap/dto/response/CreateMyMapListRes.java
  src/main/java/com/ureca/uhyu/domain/mymap/dto/response/UpdateMyMapListRes.java
  src/main/java/com/ureca/uhyu/domain/mymap/service/MyMapService.java
  src/main/java/com/ureca/uhyu/domain/recommendation/api/FastApiRecommendationClient.java
  src/main/java/com/ureca/uhyu/domain/recommendation/dto/response/RecommendationRes.java
  src/main/java/com/ureca/uhyu/domain/recommendation/entity/Recommendation.java
  src/main/java/com/ureca/uhyu/domain/recommendation/event/RecommendationEvent.java
  src/main/java/com/ureca/uhyu/domain/recommendation/repository/RecommendationRepository.java
  src/main/java/com/ureca/uhyu/domain/recommendation/repository/RecommendationRepositoryCustom.java
  src/main/java/com/ureca/uhyu/domain/recommendation/repository/RecommendationRepositoryCustomImpl.java
  src/main/java/com/ureca/uhyu/domain/user/controller/UserController.java
  src/main/java/com/ureca/uhyu/domain/user/dto/request/ActionLogsReq.java
  src/main/java/com/ureca/uhyu/domain/user/dto/request/UserOnboardingReq.java
  src/main/java/com/ureca/uhyu/domain/user/dto/response/BestBrandListRes.java
  src/main/java/com/ureca/uhyu/domain/user/dto/response/BookmarkRes.java
  src/main/java/com/ureca/uhyu/domain/user/dto/response/UserInfoRes.java
  src/main/java/com/ureca/uhyu/domain/user/dto/response/UserOnboardingRes.java
  src/main/java/com/ureca/uhyu/domain/user/entity/User.java
  src/main/java/com/ureca/uhyu/domain/user/repository/actionLogs/ActionLogsRepositoryCustom.java
  src/main/java/com/ureca/uhyu/domain/user/repository/actionLogs/ActionLogsRepositoryCustomImpl.java
  src/main/java/com/ureca/uhyu/domain/user/repository/bookmark/BookmarkRepository.java
  src/main/java/com/ureca/uhyu/domain/user/repository/bookmark/BookmarkRepositoryCustom.java
  src/main/java/com/ureca/uhyu/domain/user/repository/bookmark/BookmarkRepositoryCustomImpl.java
  src/main/java/com/ureca/uhyu/domain/user/repository/history/HistoryRepositoryCustom.java
  src/main/java/com/ureca/uhyu/domain/user/repository/history/HistoryRepositoryCustomImpl.java
  src/main/java/com/ureca/uhyu/global/config/PermitAllURI.java
  src/main/java/com/ureca/uhyu/global/config/QuerydslConfig.java
  src/main/java/com/ureca/uhyu/global/config/SecurityConfig.java
  src/main/java/com/ureca/uhyu/global/config/SwaggerConfig.java
  src/main/java/com/ureca/uhyu/global/util/S3Uploader.java
  src/main/java/com/ureca/uhyu/global/util/TokenCookieUtil.java
  src/test/java/com/ureca/uhyu/domain/map/service/MapServiceImplTest.java
  src/test/java/com/ureca/uhyu/domain/user/service/UserServiceTest.java
Labels: ♻️ 리펙토링
